name: CI test

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:
    
permissions:
  contents: write
jobs:
  test_pr_sources:
    runs-on: self-hosted
    steps:
      - name: Check success of CI workflow
        run: |
          if [ ${{ github.event.workflow_run.conclusion }} != "success" ]; then
            echo "CI workflow failed"
            exit 1
          fi
      - name: repo init
        # check who dispatched the workflow
        run: |
          if [ ${{ github.event_name }} == "workflow_run" ] || [ ${{ github.event_name }} == "workflow_dispatch" ]; then
            repo init -u https://github.com/iesy-gmbh/yocto-bsp-manifest -b ci-scarthgap-imx8mm -m iesy-osm-imx8m.xml
          fi
        # else: dispatch by PR
      - name: repo sync
        run: repo sync
      - name: run docker
        run: |
          docker run --device=/dev/kvm:/devb/kvm --device=/dev/net/tun:/dev/net/tun --cap-add NET_ADMIN --hostname buildserver -it -v /tftpboot:/tftpboot -v `pwd`:/home/build/work -e MACHINE=iesy-imx8mm-eva-mi-v1 -e DISTRO=iesy-wayland -e EULA=1 yoctocontainer
