name: CI test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    
permissions:
  contents: write
jobs:
  test_pr_sources:
    runs-on: self-hosted
    steps:
      - name: get PR branch name from env.PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BRANCH=$(gh pr view ${{ env.PR_NUMBER }} --json headRefName -q .headRefName)
          echo "::set-env name=PR_BRANCH::$PR_BRANCH"   
      - name: repo init # get branch name from PR env.PR_NUMBER
        run: repo init -u https://github.com/iesy-gmbh/yocto-bsp-manifest -b ${{ env.PR_BRANCH }} -m iesy-osm-imx8m.xml
      - name: repo sync
        run: repo sync
      - name: run docker
        run: |
          docker run --device=/dev/kvm:/devb/kvm --device=/dev/net/tun:/dev/net/tun --cap-add NET_ADMIN --hostname buildserver -it -v /tftpboot:/tftpboot -v `pwd`:/home/build/work -e MACHINE=iesy-imx8mm-eva-mi-v1 -e DISTRO=iesy-wayland -e EULA=1 yoctocontainer
